version: '3'

services:
  nginx:
    depends_on:
      - "appserver_debug"

  appserver:
    volumes:
      - "./servers/mailhog.eisenhardt.php.ini:/usr/local/etc/php/conf.d/mailhog.eisenhardt.php.ini"
      - "./servers/eisenhardt.ssmtp.conf:/etc/ssmtp/ssmtp.conf"
    depends_on:
      - "mailhog"

  appserver_debug:
    image: "maxbucknell/php:{{version}}-xdebug"
    networks:
      - "eisenhardt"
    volumes:
      - "..:/mnt/magento"
      - "./servers/mailhog.eisenhardt.php.ini:/usr/local/etc/php/conf.d/mailhog.eisenhardt.php.ini"
      - "./servers/eisenhardt.ssmtp.conf:/etc/ssmtp/ssmtp.conf"
      - "./servers/eisenhardt.php.ini:/usr/local/etc/php/php.ini"
      - "./servers/eisenhardt.php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf"

  mailhog:
    image: "mailhog/mailhog"
    user: "root"
    expose:
      - "25"
      - "80"
    environment:
      MH_SMTP_BIND_ADDR: "0.0.0.0:25"
      MH_UI_BIND_ADDR: "0.0.0.0:80"
      MH_API_BIND_ADDR: "0.0.0.0:80"
      MH_HOSTNAME: "mailhog"
      MH_MAILDIR_PATH: "/mnt/mail"
      MH_STORAGE: "maildir"
    volumes:
      - "./mail:/mnt/mail"
    networks:
      - "eisenhardt"
